spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/mariadb
    username: root
    password: sa
    platform: mysql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      enabled: true
      location: /public
      max-request-size: 10MB
      max-file-size: 10MB

server:
  tomcat:
    basedir: /public